name: Publish Helm Chart to ghcr.io

on:
  push:
    tags: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      - name: Release Helm Chart
        id: release-chart
        run: |
          sed -i "s/0.0.1/${{ github.ref_name }}/g" charts/Chart.yaml
          helm package charts/
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login --password-stdin -u ${{ github.repository_owner }} ghcr.io/${{ github.repository_owner }}
          helm push cluster-template-examples-${{ github.ref_name }}.tgz oci://ghcr.io/${{ github.repository_owner }}